server:
  port: 8080
  servlet:
    context-path: /digitalbooking
    session:
      timeout: 21600s
springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db.ctd.academy:3306/0523TDPRON2C03LAED1021PT_GRUPO1
    username: 0523TDPRON2C03LAED1021PT_GRUPO1
    password: iele4aiR
aws:
  profile: default
  s3:
    bucketname: c3-e1-digital-booking
    imagepath: img
email:
  subject: Activar Cuenta
  urlvalidation: http://localhost:5173/user/activate?token=%s
  subjectlogin: Cuenta Activada
  urllogin: http://localhost:5173/login

app:
  jwtSecret: 95a59bb848e94d00842bb39ecf6f8fcf
  jwtExpirationMs: 86400000